"""Commands for the Mailchimp /account-exports API resource.

Auto-generated by cli_anything/mailchimp/_codegen/generate.py.
Do not edit manually — re-run the generator to update.
"""

import click


@click.group("account-exports")
def account_exports_group():
    """account-exports resource commands."""


@account_exports_group.command("list")
@click.option("--fields", default=None, help="A comma-separated list of fields to return. Reference parameters of sub-objects ")
@click.option("--exclude-fields", default=None, help="A comma-separated list of fields to exclude. Reference parameters of sub-objects")
@click.option("--count", default=None, type=int, help="The number of records to return. Default value is 10. Maximum value is 1000")
@click.option("--offset", default=None, type=int, help="Used for [pagination](https://mailchimp.com/developer/marketing/docs/methods-par")
@click.option("--extra-params", default=None, help="Extra query params as JSON object, e.g. '{\"key\":\"val\"}'")
@click.pass_context
def _cmd_list_(ctx, fields, exclude_fields, count, offset, extra_params):
    """List account exports"""
    from cli_anything.mailchimp.core.client import get_client, MailchimpError
    from cli_anything.mailchimp.utils.output import _out, _out_ok, _out_err
    import json as _json
    client = get_client()
    path = f"/account-exports"
    params = {k: v for k, v in {
        "fields": fields,
        "exclude_fields": exclude_fields,
        "count": count,
        "offset": offset,
    }.items() if v is not None}
    if extra_params:
        params.update(_json.loads(extra_params))
    try:
        result = client.get(path, params=params or None)
    except MailchimpError as e:
        _out_err(e.status, e.title, e.detail, e.raw)
        return
    _out(result)

@account_exports_group.command("create")
@click.option("--data", default=None, help="Request body as JSON string.")
@click.option("--extra-params", default=None, help="Extra query params as JSON object, e.g. '{\"key\":\"val\"}'")
@click.pass_context
def _cmd_create(ctx, data, extra_params):
    """Add export"""
    from cli_anything.mailchimp.core.client import get_client, MailchimpError
    from cli_anything.mailchimp.utils.output import _out, _out_ok, _out_err
    import json as _json
    client = get_client()
    path = f"/account-exports"
    params = {}
    if extra_params:
        params.update(_json.loads(extra_params))
    body = _json.loads(data) if data else None
    try:
        result = client.post(path, json=body, params=params or None)
    except MailchimpError as e:
        _out_err(e.status, e.title, e.detail, e.raw)
        return
    _out(result)
