"""Commands for the Mailchimp /activity-feed API resource.

Auto-generated by cli_anything/mailchimp/_codegen/generate.py.
Do not edit manually — re-run the generator to update.
"""

import click


@click.group("activity-feed")
def activity_feed_group():
    """activity-feed resource commands."""


@activity_feed_group.command("list")
@click.option("--count", default=None, type=int, help="The number of records to return. Default value is 10. Maximum value is 1000")
@click.option("--offset", default=None, type=int, help="Used for [pagination](https://mailchimp.com/developer/marketing/docs/methods-par")
@click.option("--extra-params", default=None, help="Extra query params as JSON object, e.g. '{\"key\":\"val\"}'")
@click.pass_context
def _cmd_list_(ctx, count, offset, extra_params):
    """Get latest chimp chatter"""
    from cli_anything.mailchimp.core.client import get_client, MailchimpError
    from cli_anything.mailchimp.utils.output import _out, _out_ok, _out_err
    import json as _json
    client = get_client()
    path = f"/activity-feed/chimp-chatter"
    params = {k: v for k, v in {
        "count": count,
        "offset": offset,
    }.items() if v is not None}
    if extra_params:
        params.update(_json.loads(extra_params))
    try:
        result = client.get(path, params=params or None)
    except MailchimpError as e:
        _out_err(e.status, e.title, e.detail, e.raw)
        return
    _out(result)
