"""Commands for the Mailchimp /conversations API resource.

Auto-generated by cli_anything/mailchimp/_codegen/generate.py.
Do not edit manually — re-run the generator to update.
"""

import click


@click.group("conversations")
def conversations_group():
    """conversations resource commands."""


@conversations_group.command("list")
@click.option("--fields", default=None, help="A comma-separated list of fields to return. Reference parameters of sub-objects ")
@click.option("--exclude-fields", default=None, help="A comma-separated list of fields to exclude. Reference parameters of sub-objects")
@click.option("--count", default=None, type=int, help="The number of records to return. Default value is 10. Maximum value is 1000")
@click.option("--offset", default=None, type=int, help="Used for [pagination](https://mailchimp.com/developer/marketing/docs/methods-par")
@click.option("--has-unread-messages", default=None, help="Whether the conversation has any unread messages.")
@click.option("--list-id", default=None, help="The unique id for the list.")
@click.option("--campaign-id", default=None, help="The unique id for the campaign.")
@click.option("--extra-params", default=None, help="Extra query params as JSON object, e.g. '{\"key\":\"val\"}'")
@click.pass_context
def _cmd_list_(ctx, fields, exclude_fields, count, offset, has_unread_messages, list_id, campaign_id, extra_params):
    """List conversations"""
    from cli_anything.mailchimp.core.client import get_client, MailchimpError
    from cli_anything.mailchimp.utils.output import _out, _out_ok, _out_err
    import json as _json
    client = get_client()
    path = f"/conversations"
    params = {k: v for k, v in {
        "fields": fields,
        "exclude_fields": exclude_fields,
        "count": count,
        "offset": offset,
        "has_unread_messages": has_unread_messages,
        "list_id": list_id,
        "campaign_id": campaign_id,
    }.items() if v is not None}
    if extra_params:
        params.update(_json.loads(extra_params))
    try:
        result = client.get(path, params=params or None)
    except MailchimpError as e:
        _out_err(e.status, e.title, e.detail, e.raw)
        return
    _out(result)

@conversations_group.command("get")
@click.argument("CONVERSATION_ID")
@click.option("--fields", default=None, help="A comma-separated list of fields to return. Reference parameters of sub-objects ")
@click.option("--exclude-fields", default=None, help="A comma-separated list of fields to exclude. Reference parameters of sub-objects")
@click.option("--extra-params", default=None, help="Extra query params as JSON object, e.g. '{\"key\":\"val\"}'")
@click.pass_context
def _cmd_get(ctx, conversation_id, fields, exclude_fields, extra_params):
    """Get conversation"""
    from cli_anything.mailchimp.core.client import get_client, MailchimpError
    from cli_anything.mailchimp.utils.output import _out, _out_ok, _out_err
    import json as _json
    client = get_client()
    path = f"/conversations/{conversation_id}"
    params = {k: v for k, v in {
        "fields": fields,
        "exclude_fields": exclude_fields,
    }.items() if v is not None}
    if extra_params:
        params.update(_json.loads(extra_params))
    try:
        result = client.get(path, params=params or None)
    except MailchimpError as e:
        _out_err(e.status, e.title, e.detail, e.raw)
        return
    _out(result)

@conversations_group.command("list-conversations-id-messages")
@click.argument("CONVERSATION_ID")
@click.option("--fields", default=None, help="A comma-separated list of fields to return. Reference parameters of sub-objects ")
@click.option("--exclude-fields", default=None, help="A comma-separated list of fields to exclude. Reference parameters of sub-objects")
@click.option("--is-read", default=None, help="Whether a conversation message has been marked as read.")
@click.option("--before-timestamp", default=None, help="Restrict the response to messages created before the set time. Uses ISO 8601 tim")
@click.option("--since-timestamp", default=None, help="Restrict the response to messages created after the set time. Uses ISO 8601 time")
@click.option("--extra-params", default=None, help="Extra query params as JSON object, e.g. '{\"key\":\"val\"}'")
@click.pass_context
def _cmd_list_conversations_id_messages(ctx, conversation_id, fields, exclude_fields, is_read, before_timestamp, since_timestamp, extra_params):
    """List messages"""
    from cli_anything.mailchimp.core.client import get_client, MailchimpError
    from cli_anything.mailchimp.utils.output import _out, _out_ok, _out_err
    import json as _json
    client = get_client()
    path = f"/conversations/{conversation_id}/messages"
    params = {k: v for k, v in {
        "fields": fields,
        "exclude_fields": exclude_fields,
        "is_read": is_read,
        "before_timestamp": before_timestamp,
        "since_timestamp": since_timestamp,
    }.items() if v is not None}
    if extra_params:
        params.update(_json.loads(extra_params))
    try:
        result = client.get(path, params=params or None)
    except MailchimpError as e:
        _out_err(e.status, e.title, e.detail, e.raw)
        return
    _out(result)

@conversations_group.command("get-conversations-id-messages-id")
@click.argument("CONVERSATION_ID")
@click.argument("MESSAGE_ID")
@click.option("--fields", default=None, help="A comma-separated list of fields to return. Reference parameters of sub-objects ")
@click.option("--exclude-fields", default=None, help="A comma-separated list of fields to exclude. Reference parameters of sub-objects")
@click.option("--extra-params", default=None, help="Extra query params as JSON object, e.g. '{\"key\":\"val\"}'")
@click.pass_context
def _cmd_get_conversations_id_messages_id(ctx, conversation_id, message_id, fields, exclude_fields, extra_params):
    """Get message"""
    from cli_anything.mailchimp.core.client import get_client, MailchimpError
    from cli_anything.mailchimp.utils.output import _out, _out_ok, _out_err
    import json as _json
    client = get_client()
    path = f"/conversations/{conversation_id}/messages/{message_id}"
    params = {k: v for k, v in {
        "fields": fields,
        "exclude_fields": exclude_fields,
    }.items() if v is not None}
    if extra_params:
        params.update(_json.loads(extra_params))
    try:
        result = client.get(path, params=params or None)
    except MailchimpError as e:
        _out_err(e.status, e.title, e.detail, e.raw)
        return
    _out(result)
