"""Commands for the Mailchimp /customer-journeys API resource.

Auto-generated by cli_anything/mailchimp/_codegen/generate.py.
Do not edit manually — re-run the generator to update.
"""

import click


@click.group("customer-journeys")
def customer_journeys_group():
    """customer-journeys resource commands."""


@customer_journeys_group.command("trigger")
@click.argument("JOURNEY_ID")
@click.argument("STEP_ID")
@click.option("--data", default=None, help="Request body as JSON string.")
@click.option("--extra-params", default=None, help="Extra query params as JSON object, e.g. '{\"key\":\"val\"}'")
@click.pass_context
def _cmd_trigger(ctx, journey_id, step_id, data, extra_params):
    """Customer Journeys API trigger for a contact"""
    from cli_anything.mailchimp.core.client import get_client, MailchimpError
    from cli_anything.mailchimp.utils.output import _out, _out_ok, _out_err
    import json as _json
    client = get_client()
    path = f"/customer-journeys/journeys/{journey_id}/steps/{step_id}/actions/trigger"
    params = {}
    if extra_params:
        params.update(_json.loads(extra_params))
    body = _json.loads(data) if data else None
    try:
        result = client.post(path, json=body, params=params or None)
    except MailchimpError as e:
        _out_err(e.status, e.title, e.detail, e.raw)
        return
    _out(result)
