"""Commands for the Mailchimp /landing-pages API resource.

Auto-generated by cli_anything/mailchimp/_codegen/generate.py.
Do not edit manually — re-run the generator to update.
"""

import click


@click.group("landing-pages")
def landing_pages_group():
    """landing-pages resource commands."""


@landing_pages_group.command("list")
@click.option("--sort-dir", default=None, help="Determines the order direction for sorted results.")
@click.option("--sort-field", default=None, help="Returns files sorted by the specified field.")
@click.option("--fields", default=None, help="A comma-separated list of fields to return. Reference parameters of sub-objects ")
@click.option("--exclude-fields", default=None, help="A comma-separated list of fields to exclude. Reference parameters of sub-objects")
@click.option("--count", default=None, type=int, help="The number of records to return. Default value is 10. Maximum value is 1000")
@click.option("--extra-params", default=None, help="Extra query params as JSON object, e.g. '{\"key\":\"val\"}'")
@click.pass_context
def _cmd_list_(ctx, sort_dir, sort_field, fields, exclude_fields, count, extra_params):
    """List landing pages"""
    from cli_anything.mailchimp.core.client import get_client, MailchimpError
    from cli_anything.mailchimp.utils.output import _out, _out_ok, _out_err
    import json as _json
    client = get_client()
    path = f"/landing-pages"
    params = {k: v for k, v in {
        "sort_dir": sort_dir,
        "sort_field": sort_field,
        "fields": fields,
        "exclude_fields": exclude_fields,
        "count": count,
    }.items() if v is not None}
    if extra_params:
        params.update(_json.loads(extra_params))
    try:
        result = client.get(path, params=params or None)
    except MailchimpError as e:
        _out_err(e.status, e.title, e.detail, e.raw)
        return
    _out(result)

@landing_pages_group.command("create")
@click.option("--data", default=None, help="Request body as JSON string.")
@click.option("--use-default-list", default=None, type=bool, help="Will create the Landing Page using the account's Default List instead of requiri")
@click.option("--extra-params", default=None, help="Extra query params as JSON object, e.g. '{\"key\":\"val\"}'")
@click.pass_context
def _cmd_create(ctx, data, use_default_list, extra_params):
    """Add landing page"""
    from cli_anything.mailchimp.core.client import get_client, MailchimpError
    from cli_anything.mailchimp.utils.output import _out, _out_ok, _out_err
    import json as _json
    client = get_client()
    path = f"/landing-pages"
    params = {k: v for k, v in {
        "use_default_list": use_default_list,
    }.items() if v is not None}
    if extra_params:
        params.update(_json.loads(extra_params))
    body = _json.loads(data) if data else None
    try:
        result = client.post(path, json=body, params=params or None)
    except MailchimpError as e:
        _out_err(e.status, e.title, e.detail, e.raw)
        return
    _out(result)

@landing_pages_group.command("delete")
@click.argument("PAGE_ID")
@click.option("--extra-params", default=None, help="Extra query params as JSON object, e.g. '{\"key\":\"val\"}'")
@click.pass_context
def _cmd_delete(ctx, page_id, extra_params):
    """Delete landing page"""
    from cli_anything.mailchimp.core.client import get_client, MailchimpError
    from cli_anything.mailchimp.utils.output import _out, _out_ok, _out_err
    import json as _json
    client = get_client()
    path = f"/landing-pages/{page_id}"
    params = {}
    if extra_params:
        params.update(_json.loads(extra_params))
    try:
        result = client.delete(path, params=params or None)
    except MailchimpError as e:
        _out_err(e.status, e.title, e.detail, e.raw)
        return
    _out_ok("Deleted.")

@landing_pages_group.command("get")
@click.argument("PAGE_ID")
@click.option("--fields", default=None, help="A comma-separated list of fields to return. Reference parameters of sub-objects ")
@click.option("--exclude-fields", default=None, help="A comma-separated list of fields to exclude. Reference parameters of sub-objects")
@click.option("--extra-params", default=None, help="Extra query params as JSON object, e.g. '{\"key\":\"val\"}'")
@click.pass_context
def _cmd_get(ctx, page_id, fields, exclude_fields, extra_params):
    """Get landing page info"""
    from cli_anything.mailchimp.core.client import get_client, MailchimpError
    from cli_anything.mailchimp.utils.output import _out, _out_ok, _out_err
    import json as _json
    client = get_client()
    path = f"/landing-pages/{page_id}"
    params = {k: v for k, v in {
        "fields": fields,
        "exclude_fields": exclude_fields,
    }.items() if v is not None}
    if extra_params:
        params.update(_json.loads(extra_params))
    try:
        result = client.get(path, params=params or None)
    except MailchimpError as e:
        _out_err(e.status, e.title, e.detail, e.raw)
        return
    _out(result)

@landing_pages_group.command("update")
@click.argument("PAGE_ID")
@click.option("--data", default=None, help="Request body as JSON string.")
@click.option("--extra-params", default=None, help="Extra query params as JSON object, e.g. '{\"key\":\"val\"}'")
@click.pass_context
def _cmd_update(ctx, page_id, data, extra_params):
    """Update landing page"""
    from cli_anything.mailchimp.core.client import get_client, MailchimpError
    from cli_anything.mailchimp.utils.output import _out, _out_ok, _out_err
    import json as _json
    client = get_client()
    path = f"/landing-pages/{page_id}"
    params = {}
    if extra_params:
        params.update(_json.loads(extra_params))
    body = _json.loads(data) if data else None
    try:
        result = client.patch(path, json=body, params=params or None)
    except MailchimpError as e:
        _out_err(e.status, e.title, e.detail, e.raw)
        return
    _out(result)

@landing_pages_group.command("publish")
@click.argument("PAGE_ID")
@click.option("--extra-params", default=None, help="Extra query params as JSON object, e.g. '{\"key\":\"val\"}'")
@click.pass_context
def _cmd_publish(ctx, page_id, extra_params):
    """Publish landing page"""
    from cli_anything.mailchimp.core.client import get_client, MailchimpError
    from cli_anything.mailchimp.utils.output import _out, _out_ok, _out_err
    import json as _json
    client = get_client()
    path = f"/landing-pages/{page_id}/actions/publish"
    params = {}
    if extra_params:
        params.update(_json.loads(extra_params))
    try:
        result = client.post(path, json=None, params=params or None)
    except MailchimpError as e:
        _out_err(e.status, e.title, e.detail, e.raw)
        return
    _out(result)

@landing_pages_group.command("unpublish")
@click.argument("PAGE_ID")
@click.option("--extra-params", default=None, help="Extra query params as JSON object, e.g. '{\"key\":\"val\"}'")
@click.pass_context
def _cmd_unpublish(ctx, page_id, extra_params):
    """Unpublish landing page"""
    from cli_anything.mailchimp.core.client import get_client, MailchimpError
    from cli_anything.mailchimp.utils.output import _out, _out_ok, _out_err
    import json as _json
    client = get_client()
    path = f"/landing-pages/{page_id}/actions/unpublish"
    params = {}
    if extra_params:
        params.update(_json.loads(extra_params))
    try:
        result = client.post(path, json=None, params=params or None)
    except MailchimpError as e:
        _out_err(e.status, e.title, e.detail, e.raw)
        return
    _out(result)

@landing_pages_group.command("list-landing-page-id-content")
@click.argument("PAGE_ID")
@click.option("--fields", default=None, help="A comma-separated list of fields to return. Reference parameters of sub-objects ")
@click.option("--exclude-fields", default=None, help="A comma-separated list of fields to exclude. Reference parameters of sub-objects")
@click.option("--extra-params", default=None, help="Extra query params as JSON object, e.g. '{\"key\":\"val\"}'")
@click.pass_context
def _cmd_list_landing_page_id_content(ctx, page_id, fields, exclude_fields, extra_params):
    """Get landing page content"""
    from cli_anything.mailchimp.core.client import get_client, MailchimpError
    from cli_anything.mailchimp.utils.output import _out, _out_ok, _out_err
    import json as _json
    client = get_client()
    path = f"/landing-pages/{page_id}/content"
    params = {k: v for k, v in {
        "fields": fields,
        "exclude_fields": exclude_fields,
    }.items() if v is not None}
    if extra_params:
        params.update(_json.loads(extra_params))
    try:
        result = client.get(path, params=params or None)
    except MailchimpError as e:
        _out_err(e.status, e.title, e.detail, e.raw)
        return
    _out(result)
