"""Commands for the Mailchimp /ping API resource.

Auto-generated by cli_anything/mailchimp/_codegen/generate.py.
Do not edit manually — re-run the generator to update.
"""

import click


@click.group("ping")
def ping_group():
    """ping resource commands."""


@ping_group.command("list")
@click.option("--extra-params", default=None, help="Extra query params as JSON object, e.g. '{\"key\":\"val\"}'")
@click.pass_context
def _cmd_list_(ctx, extra_params):
    """Ping"""
    from cli_anything.mailchimp.core.client import get_client, MailchimpError
    from cli_anything.mailchimp.utils.output import _out, _out_ok, _out_err
    import json as _json
    client = get_client()
    path = f"/ping"
    params = {}
    if extra_params:
        params.update(_json.loads(extra_params))
    try:
        result = client.get(path, params=params or None)
    except MailchimpError as e:
        _out_err(e.status, e.title, e.detail, e.raw)
        return
    _out(result)
