"""Commands for the Mailchimp /search-campaigns API resource.

Auto-generated by cli_anything/mailchimp/_codegen/generate.py.
Do not edit manually — re-run the generator to update.
"""

import click


@click.group("search-campaigns")
def search_campaigns_group():
    """search-campaigns resource commands."""


@search_campaigns_group.command("list")
@click.option("--fields", default=None, help="A comma-separated list of fields to return. Reference parameters of sub-objects ")
@click.option("--exclude-fields", default=None, help="A comma-separated list of fields to exclude. Reference parameters of sub-objects")
@click.option("--query", default=None, help="The search query used to filter results.")
@click.option("--extra-params", default=None, help="Extra query params as JSON object, e.g. '{\"key\":\"val\"}'")
@click.pass_context
def _cmd_list_(ctx, fields, exclude_fields, query, extra_params):
    """Search campaigns"""
    from cli_anything.mailchimp.core.client import get_client, MailchimpError
    from cli_anything.mailchimp.utils.output import _out, _out_ok, _out_err
    import json as _json
    client = get_client()
    path = f"/search-campaigns"
    params = {k: v for k, v in {
        "fields": fields,
        "exclude_fields": exclude_fields,
        "query": query,
    }.items() if v is not None}
    if extra_params:
        params.update(_json.loads(extra_params))
    try:
        result = client.get(path, params=params or None)
    except MailchimpError as e:
        _out_err(e.status, e.title, e.detail, e.raw)
        return
    _out(result)
