"""Commands for the Mailchimp /surveys API resource.

Auto-generated by cli_anything/mailchimp/_codegen/generate.py.
Do not edit manually — re-run the generator to update.
"""

import click


@click.group("surveys")
def surveys_group():
    """surveys resource commands."""


@surveys_group.command("create-email")
@click.argument("LIST_ID")
@click.argument("SURVEY_ID")
@click.option("--extra-params", default=None, help="Extra query params as JSON object, e.g. '{\"key\":\"val\"}'")
@click.pass_context
def _cmd_create_email(ctx, list_id, survey_id, extra_params):
    """Create a Survey Campaign"""
    from cli_anything.mailchimp.core.client import get_client, MailchimpError
    from cli_anything.mailchimp.utils.output import _out, _out_ok, _out_err
    import json as _json
    client = get_client()
    path = f"/lists/{list_id}/surveys/{survey_id}/actions/create-email"
    params = {}
    if extra_params:
        params.update(_json.loads(extra_params))
    try:
        result = client.post(path, json=None, params=params or None)
    except MailchimpError as e:
        _out_err(e.status, e.title, e.detail, e.raw)
        return
    _out(result)

@surveys_group.command("publish")
@click.argument("LIST_ID")
@click.argument("SURVEY_ID")
@click.option("--extra-params", default=None, help="Extra query params as JSON object, e.g. '{\"key\":\"val\"}'")
@click.pass_context
def _cmd_publish(ctx, list_id, survey_id, extra_params):
    """Publish a Survey"""
    from cli_anything.mailchimp.core.client import get_client, MailchimpError
    from cli_anything.mailchimp.utils.output import _out, _out_ok, _out_err
    import json as _json
    client = get_client()
    path = f"/lists/{list_id}/surveys/{survey_id}/actions/publish"
    params = {}
    if extra_params:
        params.update(_json.loads(extra_params))
    try:
        result = client.post(path, json=None, params=params or None)
    except MailchimpError as e:
        _out_err(e.status, e.title, e.detail, e.raw)
        return
    _out(result)

@surveys_group.command("unpublish")
@click.argument("LIST_ID")
@click.argument("SURVEY_ID")
@click.option("--extra-params", default=None, help="Extra query params as JSON object, e.g. '{\"key\":\"val\"}'")
@click.pass_context
def _cmd_unpublish(ctx, list_id, survey_id, extra_params):
    """Unpublish a Survey"""
    from cli_anything.mailchimp.core.client import get_client, MailchimpError
    from cli_anything.mailchimp.utils.output import _out, _out_ok, _out_err
    import json as _json
    client = get_client()
    path = f"/lists/{list_id}/surveys/{survey_id}/actions/unpublish"
    params = {}
    if extra_params:
        params.update(_json.loads(extra_params))
    try:
        result = client.post(path, json=None, params=params or None)
    except MailchimpError as e:
        _out_err(e.status, e.title, e.detail, e.raw)
        return
    _out(result)
